import type { DesignSystem } from '../types/design-system';

export function generateMainCss(designSystem: DesignSystem, prefix: string): string {
  const googleFonts = designSystem.fonts
    .filter((f) => f.isGoogle)
    .map((f) => {
      const weights = f.weights.join(';');
      const family = f.family.replace(/\s+/g, '+');
      return `@import url('https://fonts.googleapis.com/css2?family=${family}:wght@${weights}&display=swap');`;
    });

  const uniqueGoogleImports = [...new Set(googleFonts)];

  return `/* ==========================================================================
   ${prefix} Theme - Generated by Huball
   ========================================================================== */

${uniqueGoogleImports.join('\n')}

/* --------------------------------------------------------------------------
   CSS Custom Properties (from extracted design tokens)
   -------------------------------------------------------------------------- */
:root {
${designSystem.colors.map((c) => `  --${prefix}-${c.name}: {{ theme.color_${c.name}.color }};`).join('\n')}

  --${prefix}-font-heading: {{ theme.font_heading.font }}, {{ theme.font_heading.fallback }};
  --${prefix}-font-body: {{ theme.font_body.font }}, {{ theme.font_body.fallback }};

  --${prefix}-section-spacing: {{ theme.section_spacing }}px;
  --${prefix}-max-width: {{ theme.max_content_width }}px;
  --${prefix}-radius: {{ theme.border_radius }}px;
}

/* --------------------------------------------------------------------------
   Reset & Base
   -------------------------------------------------------------------------- */
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  scroll-behavior: smooth;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  font-family: var(--${prefix}-font-body);
  font-size: 16px;
  line-height: 1.6;
  color: var(--${prefix}-text_primary);
  background-color: var(--${prefix}-background);
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--${prefix}-font-heading);
  line-height: 1.2;
  font-weight: 700;
  color: var(--${prefix}-text_primary);
}

h1 { font-size: clamp(2rem, 5vw, 3.5rem); }
h2 { font-size: clamp(1.5rem, 4vw, 2.5rem); }
h3 { font-size: clamp(1.25rem, 3vw, 1.75rem); }
h4 { font-size: 1.25rem; }

p {
  margin-bottom: 1rem;
}

a {
  color: var(--${prefix}-primary);
  text-decoration: none;
  transition: color 0.2s ease;
}

a:hover {
  opacity: 0.8;
}

img {
  max-width: 100%;
  height: auto;
  display: block;
}

/* --------------------------------------------------------------------------
   HubSpot DnD System Resets (required for drag-and-drop areas)
   -------------------------------------------------------------------------- */
.dnd-section {
  padding: 0;
}

.dnd-section > .row-fluid {
  max-width: var(--${prefix}-max-width);
  margin: 0 auto;
}

.dnd-section .dnd-column {
  padding: 0;
}

.row-fluid {
  display: flex;
  flex-wrap: wrap;
}

.row-fluid [class*="span"] {
  min-height: 1px;
}

@media (max-width: 767px) {
  .row-fluid [class*="span"] {
    width: 100% !important;
    margin-left: 0 !important;
  }
}

/* --------------------------------------------------------------------------
   Layout Utilities
   -------------------------------------------------------------------------- */
.${prefix}-container {
  max-width: var(--${prefix}-max-width);
  margin: 0 auto;
  padding: 0 1.5rem;
}

.${prefix}-section {
  padding: var(--${prefix}-section-spacing) 0;
}

.${prefix}-section--alt {
  background-color: var(--${prefix}-surface);
}

/* --------------------------------------------------------------------------
   Buttons
   -------------------------------------------------------------------------- */
.${prefix}-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.75rem 1.75rem;
  font-family: var(--${prefix}-font-body);
  font-size: 1rem;
  font-weight: 600;
  border: none;
  border-radius: var(--${prefix}-radius);
  cursor: pointer;
  text-decoration: none;
  transition: transform 0.2s ease, box-shadow 0.2s ease, opacity 0.2s ease;
}

.${prefix}-btn:hover {
  transform: translateY(-1px);
  opacity: 0.9;
}

.${prefix}-btn--primary {
  background-color: var(--${prefix}-primary);
  color: #ffffff;
}

.${prefix}-btn--secondary {
  background-color: transparent;
  color: var(--${prefix}-primary);
  border: 2px solid var(--${prefix}-primary);
}

/* --------------------------------------------------------------------------
   Scroll Reveal Animation
   -------------------------------------------------------------------------- */
.${prefix}-reveal {
  opacity: 0;
  transform: translateY(20px);
  transition: opacity 0.6s ease, transform 0.6s ease;
}

.${prefix}-reveal.is-visible {
  opacity: 1;
  transform: translateY(0);
}

/* --------------------------------------------------------------------------
   Responsive
   -------------------------------------------------------------------------- */
@media (max-width: 1023px) {
  .${prefix}-container {
    padding: 0 1.25rem;
  }
}

@media (max-width: 767px) {
  .${prefix}-container {
    padding: 0 1rem;
  }

  .${prefix}-section {
    padding: calc(var(--${prefix}-section-spacing) * 0.6) 0;
  }
}
`;
}
