export function generateMainJs(prefix: string): string {
  return `/* ==========================================================================
   ${prefix} Theme - JavaScript
   Generated by Huball
   ========================================================================== */

document.addEventListener('DOMContentLoaded', function () {
  // ---- Scroll Reveal ----
  const revealElements = document.querySelectorAll('.${prefix}-reveal');
  if (revealElements.length > 0 && 'IntersectionObserver' in window) {
    const observer = new IntersectionObserver(
      function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1 }
    );
    revealElements.forEach(function (el) {
      observer.observe(el);
    });
  } else {
    // Fallback: show all
    revealElements.forEach(function (el) {
      el.classList.add('is-visible');
    });
  }

  // ---- Header Scroll Detection ----
  var header = document.querySelector('.${prefix}-header');
  if (header) {
    var scrollThreshold = 50;
    window.addEventListener('scroll', function () {
      if (window.scrollY > scrollThreshold) {
        header.classList.add('is-scrolled');
      } else {
        header.classList.remove('is-scrolled');
      }
    });
  }

  // ---- Mobile Menu Toggle ----
  var menuToggle = document.querySelector('.${prefix}-header__toggle');
  var mobileNav = document.querySelector('.${prefix}-header__nav');
  if (menuToggle && mobileNav) {
    menuToggle.addEventListener('click', function () {
      var isOpen = mobileNav.classList.toggle('is-open');
      menuToggle.setAttribute('aria-expanded', String(isOpen));
    });
  }

  // ---- Smooth Scroll for Anchor Links ----
  document.querySelectorAll('a[href^="#"]').forEach(function (link) {
    link.addEventListener('click', function (e) {
      var target = document.querySelector(this.getAttribute('href'));
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });
});
`;
}
